services:
  naarad:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TZ=IST
    volumes:
      - naarad-cache:/var/cache/ntfy
    ports:
      - "8000:8000"
    healthcheck:
        test: ["CMD-SHELL", "wget -q --tries=1 http://localhost:8000/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true' || exit 1"]
        interval: 60s
        timeout: 10s
        retries: 3
        start_period: 40s
    restart: unless-stopped

volumes:
  naarad-cache: